### ISSUE TITLE
TODO: implement Dirichlet embeddings

### ISSUE THREAD

**Issue by eigenfoo** [eigenfoo/dirichlet-embeddings#10]
Absent of data, it sounds risky to try this. However, some of the code can be very easily done.

- [ ] Figure out a closed-form formula for the expected likelihood of two Dirichlet distributions, or figure out some workaround (perhaps considering the negative KL divergence as a similarity measure?)
- [ ] Reparameterize the code: currently there's `mu` and `sigma`, but it should be `alpha` and `beta`, with all the accompanying changes.

**Comment by Jped** [comment]
According to our schedule we have till the 21st for this no?

**Comment by eigenfoo** [comment]
Move fast and break things!!

**Comment by eigenfoo** [comment]
See #12
